### ISSUE TITLE
Private repo not working

### ISSUE THREAD

**Issue by KammererTob** [zeit/hazel#39]
Not sure if the documenation is not accurate enough or i am doing something wrong, but i cannot get the setup to run properly.
This is my command:
`now -e TOKEN=@github-token -e ACCOUNT="MyAccount" -e REPOSITORY="MyRespository" -e PORT="80" zeit/hazel`

This is the message i get immediatly and i need to supply the password for my ssh file:
> Didn't find directory. Searching on GitHub...

And this is the error i am getting after ~30 seconds:
> Error! Unexpected error. Please try again later. (An unexpected internal error occurred)

What am i doing wrong?

**Comment by KammererTob** [comment]
I initially closed the issue, because i thought that it wasn't possible to proxy a private repo through to the application to update, but now i read that it should indeed be possible. So additionally to the problem above: Is it possible to use a private GitHub Repository with Hazel, without needing to own a server for a proxy.

**Comment by onekiloparsec** [comment]
I have the exact same question. Using the following workflow:

```now secret add github_api_token <my private token>``` (scope: `repo`)

Then: `now -e TOKEN=@github_api_token zeit/hazel`

I get:

```
> Didn't find directory. Searching on GitHub...
> Deploying GitHub repository "zeit/hazel" under <email address>
> Please enter values for the following environment variables:
> ACCOUNT <account>
> REPOSITORY <repo>
> Using Node.js 8.9.4 (default)
> Ready! https://hazel-server-gvkssoyick.now.sh (copied to clipboard) [16s]
> You (<email address>) are on the OSS plan. Your code and logs will be made public.
> NOTE: You can use `now --public` to skip this prompt
> Initializing…
> Building
> ▲ npm install
> ✓ Using "package-lock.json"
> ⧗ Installing 19 main dependencies…
> ✓ Installed 872 modules [12s]
> ▲ npm start
> > hazel-server@3.0.1 start /home/nowuser/src
> > micro -p ${PORT:-3000} lib/server.js
> micro: Accepting connections on port 3000
> (node:147) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: GitHub API responded with 404 for url https://api.github.com/repos/onekiloparsec/onekiloparsec/arcsecond.uploader/releases?per_page=100
> (node:147) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> Deployment complete!
```

And when visiting the deploy, I get a 404 when tryingn to access a download.

**Comment by KammererTob** [comment]
I tried to debug `now` with a **public**  repository and this is what it says:

> [debug] Retrying: Error: An unexpected internal error occurred
Error: An unexpected internal error occurred
    at module.exports.EventEmitter.create.deployment.retry (C:\snapshot\now-cli\dist\now.js:437:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
> [debug] get files ready for deployment: 0.298ms
> [debug] v2/now/deployments: 1266.614ms
> [debug] Retrying: Error: An unexpected internal error occurred
Error: An unexpected internal error occurred
    at module.exports.EventEmitter.create.deployment.retry (C:\snapshot\now-cli\dist\now.js:437:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
> [debug] get files ready for deployment: 0.349ms
> [debug] v2/now/deployments: 1211.761ms
> [debug] Retrying: Error: An unexpected internal error occurred
Error: An unexpected internal error occurred
    at module.exports.EventEmitter.create.deployment.retry (C:\snapshot\now-cli\dist\now.js:437:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
> [debug] get files ready for deployment: 0.383ms
> [debug] v2/now/deployments: 1143.849ms
> [debug] error: Error: An unexpected internal error occurred
Error: An unexpected internal error occurred
    at module.exports.EventEmitter.create.deployment.retry (C:\snapshot\now-cli\dist\now.js:437:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
> Error! Unexpected error. Please try again later. (An unexpected internal error occurred)

Might be a problem with now rather than hazel. Hard to grasp what's going on, since the error is not very specific. I also tried to disable any firewall/anti-virus.

**Comment by onekiloparsec** [comment]
I removed my comment because I actually succeeded, with a private repo. I use the workflow: `now secret add github_token <token>` then, `now -e TOKEN=<github_token> zeit/hazel` and... it worked.

**Comment by KammererTob** [comment]
@onekiloparsec Yeah i think my problem is not related to the private repository since i also cannot deploy when using a public repository.

**Comment by mcverticchio** [comment]
I generated a token with private repo access.  I am on a team that has access to our project. I was not able to deploy an update server following the workflow above, but my coworker was able to following the same steps.  Sounds like a bug?

My error:  
> Didn't find directory. Searching on GitHub...   

Workflow: 
`now secret add my_token <token>`
`now -e TOKEN=my_token zeit/hazel`

**Comment by backroot** [comment]
This issue resolve in my pull request #98 .
Example for autoUpdater.ts.
```
import { autoUpdater } from "electron-updater";

const server = "https://hazel-xxxx.vercel.app";
const feed = `${server}/update/${process.platform}/${app.getVersion()}`;

autoUpdater.setFeedURL(feed);
```
