### ISSUE TITLE
Unhandled rejection: TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by mashrulhaque** [zeit/hazel#77]
After deploying hazel, I get the following error:

2019-10-30T12:02:44.603Z	3adf55a3-0bba-4708-98c7-054a6a66ea2e	Unhandled rejection: TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at exports.overview (/var/task/lib/routes.js:185:12)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
Duration: 263.02 ms  Billed Duration: 300 ms  Memory Size: 3008 MB  Max Memory Used: 32 MB	
RequestId: 3adf55a3-0bba-4708-98c7-054a6a66ea2e Process exited before completing request

My project is on a private repository on github. I am using the following command:

now -e ACCOUNT="mashrulhaque" -e REPOSITORY="taskmanager" -e TOKEN="<TOKEN>" -e URL="https://api.github.com/repos/mashrulhaque/taskmanager/releases?access_token=<TOKEN>"

**Comment by mashrulhaque** [comment]
My repo did not have any releases. Creating a release solved the issue. closing the issue
