### ISSUE TITLE
Problem Downloading Releases from Private Github Repos

### ISSUE THREAD

**Issue by Vinipux322** [zeit/hazel#80]
START RequestId: 2c5ddea1-eb27-41dc-9b0a-05688d6d0bfe Version: $LATEST
2019-12-11T14:14:26.514Z	2c5ddea1-eb27-41dc-9b0a-05688d6d0bfe	Unhandled rejection: Error: GitHub API responded with 401 for url https://api.github.com/repos/Vinipux322/urp-eup-converter/releases?per_page=100
    at retry (/var/task/lib/cache.js:89:17)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
END RequestId: 2c5ddea1-eb27-41dc-9b0a-05688d6d0bfe
REPORT RequestId: 2c5ddea1-eb27-41dc-9b0a-05688d6d0bfe	Duration: 7849.23 ms	Billed Duration: 7900 ms	Memory Size: 1024 MB	Max Memory Used: 30 MB	
RequestId: 2c5ddea1-eb27-41dc-9b0a-05688d6d0bfe Process exited before completing request

**Comment by jamo** [comment]
Are you passing in the GitHub API token with correct permissions?
See `TOKEN` in https://github.com/zeit/hazel#options

**Comment by Vinipux322** [comment]
Yep, i fixed it, thx
